version="0.3.1"

[scripts]
dev.subcommands.build = [
	"cd examples/showcase",
	"bonnie build --watch"
]
dev.subcommands.serve.cmd = [
	"cd examples/showcase",
	"bonnie serve %server"
]
dev.subcommands.serve.args = [ "server" ]
dev.subcommands.cli = [
	"cd packages/perseus-cli",
    # We need to copy in the directory where we actually work on the subcrate
    "cd ../perseus-cli",
    "rm -rf ./.perseus",
    "cp -r ../../examples/cli/.perseus/ .perseus/",
    "mv .perseus/Cargo.toml .perseus/Cargo.toml.old",
    "mv .perseus/server/Cargo.toml .perseus/server/Cargo.toml.old",
	"cargo run -- %%"
]
build = "cargo build"
test = "cargo watch -x \"test\""
check = "cargo check && cargo fmt -- --check && cargo clippy && cargo test" # This will be run on CI as well
# Hosts the book locally
doc = [
	"cd docs",
	"mdbook serve"
]

# Releases the project (maintainers only)
# We commit all staged files so we can manually bump the Cargo version
release = "standard-version --sign --commit-all && git push --follow-tags origin main"

# Publishes each package
publish = [
    "cd packages/perseus",
    "cargo publish %%",
    # The CLI needs the `.perseus/` directory copied in for packaging (and we need to rename `Cargo.toml` to `Cargo.toml.old`)
    "cd ../perseus-cli",
    "rm -rf ./.perseus",
    "cp -r ../../examples/cli/.perseus/ .perseus/",
    "mv .perseus/Cargo.toml .perseus/Cargo.toml.old",
    "mv .perseus/server/Cargo.toml .perseus/server/Cargo.toml.old",
    "cargo publish --allow-dirty %%", # Without this flag, `.perseus` will be a problem because it's not in Git
    # We delay this so that `crates.io` can have time to host the core
    "cd ../perseus-actix-web",
    "cargo publish %%"
]
