version="0.3.1"

[scripts]
dev.subcommands.build = [
	"cd examples/showcase",
	"bonnie build --watch"
]
dev.subcommands.serve = [
	"cd examples/showcase",
	"bonnie serve"
]
build = "cargo build"
test = "cargo watch -x \"test\""
check = "cargo check && cargo fmt -- --check && cargo clippy && cargo test" # This will be run on CI as well
# Hosts the book locally
doc = [
	"cd docs",
	"mdbook serve"
]

# Releases the project (maintainers only)
# We commit all staged files so we can manually bump the Cargo version
release = "standard-version --sign --commit-all && git push --follow-tags origin main"