[workspace]
members = [
	"packages/perseus",
	"packages/perseus-actix-web",
	"packages/perseus-cli",
    # TODO remake showcase app for CLI
    "examples/showcase",
	# "examples/showcase/app",
	# "examples/showcase/server-actix-web",
    "examples/cli",
    # We have the CLI subcrates as workspace members so we can actively develop on them
    # They also can't be a workspace until nested workspaces are supported
    "examples/cli/.perseus",
    "examples/cli/.perseus/server",
    "examples/basic",
    "examples/i18n"
]
