# This crate defines the user's app in terms that WASM can understand, making development significantly simpler.
# IMPORTANT: spacing matters in this file for runtime replacements, do NOT change it!

[package]
name = "perseus-cli-server"
version = "0.1.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# We alias here because the package name will change based on whatever's in the user's manifest
app = { package = "perseus-example-cli", path = "../../" }

perseus-actix-web = { path = "../../../../packages/perseus-actix-web" }
actix-web = "3.3"
futures = "0.3"

# Needed until Sycamore #230 is released (becomes relevant when excluded from user's workspaces)
[patch.crates-io]
sycamore = { git = "https://github.com/arctic-hen7/sycamore", branch = "router-clone-stable" }
sycamore-router = { git = "https://github.com/arctic-hen7/sycamore", branch = "router-clone-stable" }
