[package]
name = "perseus-actix-web"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
perseus = { path = "../perseus" }
actix-web = "3.3"
actix-files = "0.5"
urlencoding = "2.1"
serde_json = "1"
error-chain = "0.12"
futures = "0.3"
sycamore = { version = "0.5.1", features = ["ssr"] }