[package]
name = "perseus-cli"
version = "0.1.0"
edition = "2018"
description = "The CLI for the Perseus frontend framework."
authors = ["arctic_hen7 <arctic_hen7@pm.me>"]
license = "MIT"
repository = "https://github.com/arctic-hen7/perseus"
homepage = "https://arctic-hen7.github.io/perseus"
readme = "../../README.md"
keywords = ["wasm", "cli", "webdev", "ssg", "ssr"]
categories = ["wasm", "development-tools", "asynchronous", "gui", "command-line-utilities"]
include = [
    "src/",
    "Cargo.toml",
    ".perseus/"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
include_dir = "0.6"
error-chain = "0.12"
cargo_toml = "0.9"
indicatif = "0.16"
console = "0.14"
serde = "1"
serde_json = "1"

[lib]
name = "lib"

[[bin]]
name = "cli"
path = "src/bin/main.rs"
