[package]
name = "perseus-cli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
perseus = { path = "../perseus" }
perseus-actix-web = { path = "../perseus-actix-web" }

[lib]
name = "lib"

[[bin]]
name = "cli"
path = "src/bin/main.rs"