contact_links:
    - name: Ask a question about Perseus and Sycamore
      url: https://discord.gg/vDwFUmm6mU
      about: Join us on the Sycamore's Discord server.
    - name: Ask a general question
      url: https://github.com/arctic-hen7/perseus/discussions/new
      about: Open a discussion.
