version="0.3.1"

[scripts]
build.cmd = [
	"cd app",
    "cargo run --bin ssg",
	"wasm-pack build --target web",
	"rollup ./main.js --format iife --file ./pkg/bundle.js"
]
build.subcommands.--watch = "find . -not -path \"./target/*\" -not -path \"./.git/*\" | entr -s \"bonnie build\""
serve = [
	"cd server",
	"cargo watch -w ../ -x \"run\""
]
