[package]
name = "perseus-website"
version = "0.3.0-beta.1"
edition = "2018"
description = "The official website for the Perseus framework."
authors = ["arctic_hen7 <arctic_hen7@pm.me>"]
license = "MIT"
repository = "https://github.com/arctic-hen7/perseus"
homepage = "https://arctic-hen7.github.io/perseus"
readme = "./README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# We use the current version of Perseus, not the local one
perseus = "0.3.0-beta.1"
sycamore = "0.6"
serde = "1"
serde_json = "1"
fluent-bundle = "0.15"
