name: Test

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Test Library
              # We need to have a `.perseus/` directory for the CLI to compile, but it doesn't need to have anything in it
              run: mkdir packages/perseus-cli/.perseus && cargo check --all && cargo fmt --all -- --check && cargo clippy --all && cargo test --all
